# this file is *not* meant to cover or endorse the use of travis, but rather to
# help confirm pull requests to this project.

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34

before_install:
    - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then bash ./.travis/install-osx.sh; fi
    - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then curl -sL -o ~/bin/gimme https://raw.githubusercontent.com/travis-ci/gimme/master/gimme; fi
    - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then chmod +x ~/bin/gimme; fi

install:
    - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo pip install tox-travis; fi
    - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get update && sudo apt-get install swig; fi
    - eval "$(gimme 1.10)"

script: make test

notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
