# this file is *not* meant to cover or endorse the use of travis, but rather to
# help confirm pull requests to this project.

matrix:
  include:
    - os: linux
      language: python
      python: 2.7
      env:
        - TOXENV=py27
        - PYTHON=2.7
    - os: linux
      language: python
      python: 3.4
      env:
        - TOXENV=py34
        - PYTHON=3.4
    - os: linux
      language: python
      python: 3.5
      env:
        - TOXENV=py35
        - PYTHON=3.5
    - os: linux
      language: python
      python: 3.6
      env:
        - TOXENV=py36
        - PYTHON=3.6
      addons:
        apt:
          sources: [deadsnakes]
          packages: [python3.6, python3.6-dev]
    - os: osx
      languague: generic
      env:
        - PYTHON=2.7
        - TOXENV=py27
    - os: osx
      languague: generic
      env:
        - PYTHON=3.4.8
        - TOXENV=py34
    - os: osx
      languague: generic
      env:
        - PYTHON=3.5.5
        - TOXENV=py35
    - os: osx
      languague: generic
      env:
        - PYTHON=3.6.5
        - TOXENV=py36

before_install:
    - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then bash ./.travis/install-osx.sh; fi
    - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then curl -sL -o ~/bin/gimme https://raw.githubusercontent.com/travis-ci/gimme/master/gimme; fi
    - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then chmod +x ~/bin/gimme; fi

install:
    - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo pip install tox-travis; fi
    - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get update && sudo apt-get install python${PYTHON}-dev; fi
    - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then mkdir swig_build && cd swig_build && wget http://prdownloads.sourceforge.net/swig/swig-3.0.12.tar.gz && tar -zxf swig-3.0.12.tar.gz && cd swig-3.0.12 && sudo ./configure --prefix=/usr && sudo make && sudo make install && cd ../../ && sudo rm -rf swig_build ; fi
    - eval "$(gimme 1.10)"
    
after_failure:
  - cat ./.tox/py34/log/py34-*.log

script: make test

notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
